//! Per-instance DXGI interception for the Nexus runtime.
//!
//! The manager attaches only to concrete factory and swap-chain objects that
//! the proxy returns or subsequently observes through `QueryInterface`. It
//! never modifies executable code or a process-wide vtable. Every detour keeps
//! the native method authoritative: the original method is called exactly once
//! and its result is returned unchanged, even if Nexus inspection, policy, or
//! rendering fails or panics.
//!
//! DXGI interface definitions are generated by the `windows` crate because
//! `windows-sys` 0.61 does not expose DXGI COM interfaces or their associated
//! structures. Public ABI boundaries continue to use
//! [`windows_sys::core::GUID`] and raw pointers, with explicit layout-preserving
//! conversions in the private SDK adapter.
//!
//! # Color-space tracking
//!
//! DXGI has no color-space getter. A newly attached swap chain therefore starts
//! with [`nexus_render::ColorSpace::Other`] and emits an explicit
//! [`ObservationField::ColorSpace`] incomplete-metadata event. Successful
//! `IDXGISwapChain3::SetColorSpace1` calls update the tracked session; failures
//! retain the prior value. Unknown native values remain open numeric values and
//! are never silently treated as SDR.

#![cfg_attr(not(all(windows, target_arch = "x86_64")), allow(dead_code))]

#[cfg(not(all(windows, target_arch = "x86_64")))]
compile_error!("nexus-dxgi supports only 64-bit Windows targets");

mod callbacks;
mod detours;
mod error;
mod event;
mod manager;
mod sdk;

pub use callbacks::{
    DxgiCallbacks, OverlayRenderer, PresentFrame, RenderCallbackError, ResizeFrame,
};
pub use error::DxgiError;
pub use event::{
    AttachOutcome, Boundary, DxgiObservationEvent, FactoryInterface, HResultDisposition,
    ObjectKind, ObservationField, ShutdownReport, SwapChainInterface,
};
pub use manager::{DxgiConfig, DxgiInterceptionManager};
pub use sdk::{factory_iid, swap_chain_iid};
