//! External oracle for the add-on ABI's byte layout.
//!
//! Every other layout check in this repository compares Rust against expectations a
//! human computed by reading a header. A shared mistake between the two therefore
//! passes silently, and a wrong offset does not fail diagnosably — it corrupts
//! third-party addon binaries at run time.
//!
//! This check removes the human from the loop. It emits the offsets Rust actually
//! produces into a C++ translation unit of `static_assert`s against the MIT-licensed
//! upstream `Nexus.h`, then compiles it with MSVC. If the two disagree, the compiler
//! says so and names the field. Nothing is linked and nothing is run: compilation
//! succeeding *is* the agreement.
//!
//! # Scope, and what this cannot cover
//!
//! `vendor/nexus-api/Nexus.h` declares `NEXUS_API_VERSION 6` and a single
//! `AddonAPI_t`, so revision 6 is the only API table it can settle. Revisions 1–5 are
//! absent from the public header and remain checked against hand-read expectations in
//! `nexus-abi`'s own tests.
//!
//! `NexusLinkData_t` is also **shorter upstream than the host's struct**: it ends at
//! `FontUI`, where the running host additionally publishes the quick-access fields.
//! Only the shared prefix is asserted here.

use std::{env, fs, path::PathBuf};

use nexus_abi::{AddonApiV6, AddonDefinitionV1, InputBindV1, NexusLinkData, Texture, Version};

/// The only target this proxy is built for, per `rust-toolchain.toml`.
///
/// `cc` reads this from the environment inside a build script; here it must be stated.
const TARGET: &str = "x86_64-pc-windows-msvc";

/// A single layout fact: a C++ expression and the value Rust computed for it.
struct Assertion {
    expression: String,
    value: usize,
    subject: String,
}

impl Assertion {
    fn new(expression: impl Into<String>, value: usize, subject: impl Into<String>) -> Self {
        Self {
            expression: expression.into(),
            value,
            subject: subject.into(),
        }
    }
}

/// Emits the offsets Rust computes and has MSVC check them against upstream `Nexus.h`.
pub fn verify_abi() -> Result<usize, String> {
    let assertions = assertions();
    let source = render(&assertions);

    let manifest = PathBuf::from(
        env::var_os("CARGO_MANIFEST_DIR")
            .ok_or_else(|| "Cargo did not provide CARGO_MANIFEST_DIR".to_owned())?,
    );
    let repository = manifest
        .parent()
        .ok_or_else(|| "the xtask manifest has no parent directory".to_owned())?;
    let include = repository.join("vendor").join("nexus-api");
    let header = include.join("Nexus.h");
    if !header.is_file() {
        return Err(format!(
            "the upstream ABI header is missing at {}\n\
             it is vendored from the MIT-licensed RaidcoreGG/Nexus-API; see PROVENANCE.md",
            header.display()
        ));
    }

    let out = repository.join("target").join("abi-oracle");
    fs::create_dir_all(&out)
        .map_err(|error| format!("failed to create {}: {error}", out.display()))?;
    let generated = out.join("abi_oracle.cpp");
    fs::write(&generated, source)
        .map_err(|error| format!("failed to write {}: {error}", generated.display()))?;

    // `cc` normally runs inside a build script and reads these from the environment.
    let mut build = cc::Build::new();
    build
        .cpp(true)
        .std("c++17")
        .file(&generated)
        .include(&include)
        .out_dir(&out)
        .target(TARGET)
        .host(TARGET)
        .opt_level(0)
        .cargo_metadata(false)
        .cargo_warnings(false)
        .cargo_debug(false);

    build.try_compile("abi_oracle").map_err(|error| {
        format!(
            "MSVC rejected the layout assertions, so Rust and upstream Nexus.h disagree.\n\
             The failing `static_assert` message names the field.\n\
             Generated translation unit: {}\n\n{error}",
            generated.display()
        )
    })?;

    Ok(assertions.len())
}

fn render(assertions: &[Assertion]) -> String {
    let mut source = String::from(
        "// Generated by `cargo run -p xtask -- verify-abi`. Do not edit.\n\
         //\n\
         // Each assertion states a layout fact Rust computed. MSVC checks it against the\n\
         // upstream header, so a shared human mistake cannot pass.\n\
         \n\
         #include <cstddef>\n\
         \n\
         #include \"Nexus.h\"\n\
         \n",
    );
    for Assertion {
        expression,
        value,
        subject,
    } in assertions
    {
        source.push_str(&format!(
            "static_assert({expression} == {value}, \"{subject}\");\n"
        ));
    }
    source
}

/// The correspondence table, deliberately flat: every line is one independent layout
/// fact, which is far easier to review than the same content split across helpers.
fn assertions() -> Vec<Assertion> {
    use core::mem::{align_of, offset_of, size_of};

    let mut assertions = Vec::new();

    // Revision 6 is the only API table the public header declares.
    assertions.push(Assertion::new(
        "NEXUS_API_VERSION",
        6,
        "the vendored header must still describe revision 6",
    ));
    assertions.push(Assertion::new(
        "sizeof(AddonAPI_t)",
        size_of::<AddonApiV6>(),
        "AddonApiV6 size",
    ));
    assertions.push(Assertion::new(
        "alignof(AddonAPI_t)",
        align_of::<AddonApiV6>(),
        "AddonApiV6 alignment",
    ));

    // Rust groups the flat upstream members into sub-tables. Each entry asserts that a
    // sub-table begins exactly where its first upstream member sits.
    let api: [(&str, usize); 19] = [
        ("SwapChain", offset_of!(AddonApiV6, swap_chain)),
        ("ImguiContext", offset_of!(AddonApiV6, imgui_context)),
        ("ImguiMalloc", offset_of!(AddonApiV6, imgui_malloc)),
        ("ImguiFree", offset_of!(AddonApiV6, imgui_free)),
        ("GUI_Register", offset_of!(AddonApiV6, renderer)),
        ("RequestUpdate", offset_of!(AddonApiV6, request_update)),
        ("Log", offset_of!(AddonApiV6, log)),
        ("GUI_SendAlert", offset_of!(AddonApiV6, ui)),
        ("Paths_GetGameDirectory", offset_of!(AddonApiV6, paths)),
        ("MinHook_Create", offset_of!(AddonApiV6, min_hook)),
        ("Events_Raise", offset_of!(AddonApiV6, events)),
        ("WndProc_Register", offset_of!(AddonApiV6, wnd_proc)),
        ("InputBinds_Invoke", offset_of!(AddonApiV6, input_binds)),
        ("GameBinds_PressAsync", offset_of!(AddonApiV6, game_binds)),
        ("DataLink_Get", offset_of!(AddonApiV6, data_link)),
        ("Textures_Get", offset_of!(AddonApiV6, textures)),
        ("QuickAccess_Add", offset_of!(AddonApiV6, quick_access)),
        (
            "Localization_Translate",
            offset_of!(AddonApiV6, localization),
        ),
        ("Fonts_Get", offset_of!(AddonApiV6, fonts)),
    ];
    for (member, offset) in api {
        assertions.push(Assertion::new(
            format!("offsetof(AddonAPI_t, {member})"),
            offset,
            format!("AddonApiV6 sub-table at upstream member {member}"),
        ));
    }

    assertions.push(Assertion::new(
        "sizeof(AddonDefinition_t)",
        size_of::<AddonDefinitionV1>(),
        "AddonDefinitionV1 size",
    ));
    assertions.push(Assertion::new(
        "alignof(AddonDefinition_t)",
        align_of::<AddonDefinitionV1>(),
        "AddonDefinitionV1 alignment",
    ));
    let definition: [(&str, usize); 11] = [
        ("Signature", offset_of!(AddonDefinitionV1, signature)),
        ("APIVersion", offset_of!(AddonDefinitionV1, api_version)),
        ("Name", offset_of!(AddonDefinitionV1, name)),
        ("Version", offset_of!(AddonDefinitionV1, version)),
        ("Author", offset_of!(AddonDefinitionV1, author)),
        ("Description", offset_of!(AddonDefinitionV1, description)),
        ("Load", offset_of!(AddonDefinitionV1, load)),
        ("Unload", offset_of!(AddonDefinitionV1, unload)),
        ("Flags", offset_of!(AddonDefinitionV1, flags)),
        ("Provider", offset_of!(AddonDefinitionV1, provider)),
        ("UpdateLink", offset_of!(AddonDefinitionV1, update_link)),
    ];
    for (member, offset) in definition {
        assertions.push(Assertion::new(
            format!("offsetof(AddonDefinition_t, {member})"),
            offset,
            format!("AddonDefinitionV1::{member}"),
        ));
    }

    assertions.push(Assertion::new(
        "sizeof(AddonVersion_t)",
        size_of::<Version>(),
        "Version size",
    ));
    let version: [(&str, usize); 4] = [
        ("Major", offset_of!(Version, major)),
        ("Minor", offset_of!(Version, minor)),
        ("Build", offset_of!(Version, build)),
        ("Revision", offset_of!(Version, revision)),
    ];
    for (member, offset) in version {
        assertions.push(Assertion::new(
            format!("offsetof(AddonVersion_t, {member})"),
            offset,
            format!("Version::{member}"),
        ));
    }

    assertions.push(Assertion::new(
        "sizeof(Keybind_t)",
        size_of::<InputBindV1>(),
        "InputBindV1 size",
    ));
    assertions.push(Assertion::new(
        "alignof(Keybind_t)",
        align_of::<InputBindV1>(),
        "InputBindV1 alignment",
    ));
    let bind: [(&str, usize); 4] = [
        ("Key", offset_of!(InputBindV1, key)),
        ("Alt", offset_of!(InputBindV1, alt)),
        ("Ctrl", offset_of!(InputBindV1, ctrl)),
        ("Shift", offset_of!(InputBindV1, shift)),
    ];
    for (member, offset) in bind {
        assertions.push(Assertion::new(
            format!("offsetof(Keybind_t, {member})"),
            offset,
            format!("InputBindV1::{member}"),
        ));
    }

    assertions.push(Assertion::new(
        "sizeof(Texture_t)",
        size_of::<Texture>(),
        "Texture size",
    ));
    let texture: [(&str, usize); 3] = [
        ("Width", offset_of!(Texture, width)),
        ("Height", offset_of!(Texture, height)),
        ("Resource", offset_of!(Texture, resource)),
    ];
    for (member, offset) in texture {
        assertions.push(Assertion::new(
            format!("offsetof(Texture_t, {member})"),
            offset,
            format!("Texture::{member}"),
        ));
    }

    // Only the prefix the public header declares. The host's struct continues past
    // FontUI with the quick-access fields, which upstream does not expose.
    let link: [(&str, usize); 9] = [
        ("Width", offset_of!(NexusLinkData, width)),
        ("Height", offset_of!(NexusLinkData, height)),
        ("Scaling", offset_of!(NexusLinkData, scaling)),
        ("IsMoving", offset_of!(NexusLinkData, is_moving)),
        (
            "IsCameraMoving",
            offset_of!(NexusLinkData, is_camera_moving),
        ),
        ("IsGameplay", offset_of!(NexusLinkData, is_gameplay)),
        ("Font", offset_of!(NexusLinkData, font)),
        ("FontBig", offset_of!(NexusLinkData, font_big)),
        ("FontUI", offset_of!(NexusLinkData, font_ui)),
    ];
    for (member, offset) in link {
        assertions.push(Assertion::new(
            format!("offsetof(NexusLinkData_t, {member})"),
            offset,
            format!("NexusLinkData::{member}"),
        ));
    }
    // Pin the boundary itself, so a future header that grows the struct is noticed
    // rather than silently leaving the tail unchecked.
    assertions.push(Assertion::new(
        "sizeof(NexusLinkData_t)",
        offset_of!(NexusLinkData, quick_access_icons_count),
        "upstream NexusLinkData_t ends where the host's quick-access fields begin",
    ));

    assertions
}

#[cfg(test)]
mod tests {
    use super::{assertions, render};

    /// A translation unit that asserts nothing still compiles, so an emptied table would
    /// make `verify-abi` pass while checking nothing at all.
    #[test]
    fn the_table_is_substantial() {
        assert!(
            assertions().len() >= 50,
            "the correspondence table has shrunk to {} facts; a nearly-empty table \
             makes the oracle vacuous",
            assertions().len()
        );
    }

    #[test]
    fn every_fact_becomes_exactly_one_static_assert() {
        let facts = assertions();
        let source = render(&facts);
        let emitted = source
            .lines()
            .filter(|line| line.starts_with("static_assert("))
            .count();
        assert_eq!(
            emitted,
            facts.len(),
            "each layout fact must emit one assertion, or some are silently dropped"
        );
    }

    #[test]
    fn the_generated_unit_includes_the_vendored_header() {
        // Without the include the assertions would not name upstream types at all, and
        // the unit would fail to compile rather than pass vacuously -- but an accidental
        // change to a system include would compile and check nothing.
        assert!(render(&assertions()).contains("#include \"Nexus.h\""));
    }
}
