//! Pins the proxy DLL's PE export names and ordinals, and embeds its version resource.

use std::{env, fs, path::PathBuf};

fn main() {
    let Some(manifest_directory) = env::var_os("CARGO_MANIFEST_DIR") else {
        panic!("Cargo did not provide CARGO_MANIFEST_DIR");
    };
    let definition = PathBuf::from(manifest_directory).join("proxy.def");

    println!("cargo::rerun-if-changed={}", definition.display());
    println!("cargo::rustc-cdylib-link-arg=/DEF:{}", definition.display());

    embed_version_resource();
}

/// Embeds a `VS_VERSION_INFO` resource so the shipped DLL carries Windows file
/// properties.
///
/// Third-party Guild Wars 2 addon managers identify the installed host by its
/// `FileVersion`; a DLL with no version resource reads as unknown and can be
/// overwritten, which would silently undo a user's swap.
///
/// The resource script is generated rather than checked in so the embedded version
/// cannot drift from the package version. `xtask verify-version` asserts the two still
/// agree in the built image. When further resources are embedded — icons, fonts, the
/// third-party notice blob — this generated script should `#include` a checked-in one
/// rather than grow inline.
fn embed_version_resource() {
    if env::var("CARGO_CFG_TARGET_OS").as_deref() != Ok("windows") {
        return;
    }

    let Some(out_directory) = env::var_os("OUT_DIR") else {
        panic!("Cargo did not provide OUT_DIR");
    };
    let Ok(version) = env::var("CARGO_PKG_VERSION") else {
        panic!("Cargo did not provide CARGO_PKG_VERSION");
    };

    let [major, minor, patch, build] = version_components(&version);
    let script = PathBuf::from(out_directory).join("version.rc");
    // Language 0x0409 (US English) with code page 1200 (UTF-16), matching the
    // "040904b0" string-block name below.
    let contents = format!(
        r#"// Generated by build.rs from CARGO_PKG_VERSION. Do not edit.
1 VERSIONINFO
FILEVERSION {major},{minor},{patch},{build}
PRODUCTVERSION {major},{minor},{patch},{build}
FILEFLAGSMASK 0x3fL
FILEFLAGS 0x0L
FILEOS 0x40004L
FILETYPE 0x2L
FILESUBTYPE 0x0L
BEGIN
    BLOCK "StringFileInfo"
    BEGIN
        BLOCK "040904b0"
        BEGIN
            VALUE "CompanyName", "Tessera contributors"
            VALUE "FileDescription", "Tessera addon host"
            VALUE "FileVersion", "{major}.{minor}.{patch}.{build}"
            VALUE "InternalName", "d3d11"
            VALUE "LegalCopyright", "Copyright (c) 2026 Tessera contributors. Apache-2.0 licensed."
            VALUE "OriginalFilename", "d3d11.dll"
            VALUE "ProductName", "Tessera"
            VALUE "ProductVersion", "{version}"
        END
    END
    BLOCK "VarFileInfo"
    BEGIN
        VALUE "Translation", 0x409, 1200
    END
END
"#
    );

    if let Err(error) = fs::write(&script, contents) {
        panic!("failed to write {}: {error}", script.display());
    }

    match embed_resource::compile(&script, embed_resource::NONE) {
        embed_resource::CompilationResult::Ok | embed_resource::CompilationResult::NotWindows => {}
        other => panic!("failed to embed the version resource: {other:?}"),
    }
}

/// Splits a package version into the four 16-bit components `VERSIONINFO` requires.
///
/// Missing components default to zero. `xtask verify-version` holds the test cases for
/// this routine, since it must agree with its copy there.
fn version_components(version: &str) -> [u16; 4] {
    // A pre-release tag or build metadata is not a version component, and its own dots
    // must not be mistaken for one: `1.2.3-rc.4` is three components, not four.
    let numeric = version.split(['-', '+']).next().unwrap_or_default();

    let mut components = [0u16; 4];
    for (component, field) in components.iter_mut().zip(numeric.split('.')) {
        *component = field.parse().unwrap_or_default();
    }
    components
}
